Vagrant.configure("2") do |config|
   
  config.vm.box = "centos/7"
  config.vm.provision "shell", path:"provision.sh"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vbguest.auto_update = false
  config.ssh.insert_key = false
  #config.ssh.password = "vagrant"
  #config.ssh.username = "vagrant"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
end
