 
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "app01"
    config.vm.network "private_network", ip:"192.168.56.11"
    config.vm.provision "shell", path: "provision.sh"
    #config.vm.synced_folder ".", "/vagrant", type: "nfs"
    #config.vm.synced_folder ".", "/vagrant", type: "rsync"
    #config.vm.provision "shell", path: "provision.sh"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vbguest.auto_update = false
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
    config.ssh.insert_key = false
  end
  