
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "db01"
    config.vm.network "private_network", ip: "192.168.56.4"
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
    config.vm.synced_folder ".", "/vagrant", type: "rsync" 
    config.vm.network "forwarded_port", guest: 3306, host: 3306
    config.ssh.insert_key = false
    config.vm.provision "shell", path: "provision.sh"
  end
    #parei na aula17